### ISSUE TITLE
Exception when creating a unit with no description

### ISSUE THREAD

**Issue by jhoerr** [indiana-university/itpeople-functions-v2#30]
The frontend allows a unit to be created without a description, so the API needs to allow it as well.

**Request**

POST /units 
{ "name": "foo"}

**Exception Detail**

```
Microsoft.EntityFrameworkCore.DbUpdateException:
  MessageText: null value in column "description" violates not-null constraint
  Detail: Failing row contains (331, foo, null, null, null, null).
  SchemaName: public
  TableName: units
  ColumnName: description
```
